"""
Константы приложения.
"""

# Статусы новелл
NOVEL_STATUS_DRAFT = "draft"
NOVEL_STATUS_PUBLISHED = "published"
NOVEL_STATUS_COMPLETED = "completed"

NOVEL_STATUSES = [
    NOVEL_STATUS_DRAFT,
    NOVEL_STATUS_PUBLISHED,
    NOVEL_STATUS_COMPLETED
]

# Жанры новелл
GENRE_FANTASY = "fantasy"
GENRE_ROMANCE = "romance"
GENRE_MYSTERY = "mystery"
GENRE_SCIFI = "science_fiction"
GENRE_HORROR = "horror"
GENRE_ADVENTURE = "adventure"
GENRE_HISTORICAL = "historical"
GENRE_CONTEMPORARY = "contemporary"
GENRE_OTHER = "other"

GENRES = [
    GENRE_FANTASY,
    GENRE_ROMANCE,
    GENRE_MYSTERY,
    GENRE_SCIFI,
    GENRE_HORROR,
    GENRE_ADVENTURE,
    GENRE_HISTORICAL,
    GENRE_CONTEMPORARY,
    GENRE_OTHER
]

# Типы AI предложений
AI_SUGGESTION_CONTINUATION = "continuation"
AI_SUGGESTION_PLOT_IDEA = "plot_idea"
AI_SUGGESTION_CHARACTER_DEVELOPMENT = "character_development"
AI_SUGGESTION_DIALOGUE = "dialogue"
AI_SUGGESTION_DESCRIPTION = "description"
AI_SUGGESTION_TITLE = "title"

AI_SUGGESTION_TYPES = [
    AI_SUGGESTION_CONTINUATION,
    AI_SUGGESTION_PLOT_IDEA,
    AI_SUGGESTION_CHARACTER_DEVELOPMENT,
    AI_SUGGESTION_DIALOGUE,
    AI_SUGGESTION_DESCRIPTION,
    AI_SUGGESTION_TITLE
]

# Лимиты
MAX_TITLE_LENGTH = 200
MAX_DESCRIPTION_LENGTH = 2000
MAX_CONTENT_LENGTH = 50000
MAX_USERNAME_LENGTH = 50
MAX_BIO_LENGTH = 500
MIN_PASSWORD_LENGTH = 8
MAX_PASSWORD_LENGTH = 128

# Пагинация
DEFAULT_PAGE_SIZE = 10
MAX_PAGE_SIZE = 100

# Время чтения
WORDS_PER_MINUTE = 200

# Файлы
MAX_FILE_SIZE = 5 * 1024 * 1024  # 5MB
ALLOWED_IMAGE_TYPES = ["image/jpeg", "image/png", "image/gif", "image/webp"]
ALLOWED_DOCUMENT_TYPES = ["text/plain", "application/pdf"]

# Рейтинги
MIN_RATING = 1
MAX_RATING = 5

# Токены
TOKEN_EXPIRE_MINUTES = 30
REFRESH_TOKEN_EXPIRE_DAYS = 7

# Email
EMAIL_VERIFICATION_EXPIRE_HOURS = 24
PASSWORD_RESET_EXPIRE_HOURS = 1 